# Site
repository: marcosevaldt/marcosevaldt.github.io
# favicon: Directory of your favicon (eg. images/favicon.ico)(optional)

# Personal info
name: Marcos Evaldt Ereno
title: PHP Developer
email: marcosevaldt@gmail.com
#website: Your website (optional)

# Social links
#twitter_username: jekyllrb
github_username:  marcosevaldt
#dribbble_username: jekyll
facebook_username: marcos.evaldt
#flickr_username: jekyll
#instagram_username: jekyll
linkedin_username: marcos-evaldt-3a3494133
#pinterest_username: jekyll
#youtube_username: jekyll
#googleplus_username: +jekyll

# About Section
# about_title: About Me (Use this to override about section title)
about_profile_image: images/profile.jpg
about_content: | # this will include new lines to allow paragraphs
  Sou um desenvolvedor PHP apaixonado por tecnologia, inovação e sempre em busca de novos desafios, me preocupo com padrões de projeto com foco na manutenção e desenvolvimento de novas funcionalidades em sistemas novos e/ou legados e sempre que posso contribuo para projetos da comunidade open-source.

# Projects Section
# projects_title: Projects #(Use this to override about projects section title)

# Experience Section
# experience_title: Experience #(Use this to override about experience section title)

# Education Section
# educaton_title: Education #(Use this to override about education section title)

# More Section
# more_title: A Little More About Me #(Use this to override about more section title)
more_content: | # this will include new lines to allow paragraphs
  Durante minha trajetória acadêmica e profissional tive a oportunidade de trabalhar com diversas tecnologias que são a minha paixão, gosto da leitura de livros técnicos e de conhecer as tecnologias emergentes do mercado, alguns tópicos que estou me aprofundando são
  - Docker
  - Kubernetes
  - Agile Methodology
  - Scrum
  - CI/CD
# Footer
footer_show_references: true

# Build settings
# theme: modern-resume-theme (Use this is you are hosting your resume yourself)
# remote_theme: sproogen/modern-resume-theme (Use this if you are hosting your resume on GitHub)

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag
